### ISSUE TITLE
homepage not working : The following ArgumentError was thrown building HomePage(dirty, state: _HomePageState#5431b): Invalid argument(s)

### ISSUE THREAD

**Issue by gorychama** [dc-exe/Health_and_Doctor_Appointment#1]
```
======== Exception caught by widgets library =======================================================
The following ArgumentError was thrown building HomePage(dirty, state: _HomePageState#5431b):
Invalid argument(s)

The relevant error-causing widget was: 
  HomePage file:///Users/mac/AndroidStudioProjects/Health_and_Doctor_Appointment/lib/mainPage.dart:25:5
When the exception was thrown, this was the stack: 
#0      _StringBase.+ (dart:core-patch/string_patch.dart:272:57)
#1      _HomePageState.build (package:health_and_doctor_appointment/screens/homePage.dart:130:32)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4612:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4495:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
...
====================================================================================================

```

**Comment by dc-exe** [comment]
I have fixed some bugs. Please try to pull and run again. Tell me if there is still a problem.
The app might be unstable in iOS as it is still under development. Please try to run on android.
